### ISSUE TITLE
GetStudentOutings 메서드 학생 UUID 존재 X -> 500뜸 (근데, 존재하는 UUID도 오류뜨는데??)

### ISSUE THREAD

**Issue by parkjinhong03** [DMS-SMS/v1-service-outing#73]
## Ex)

- v1/students/uuid/student-123412341234 -> 404
- v1/students/uuid/student-123412341234/outings -> 500
<br>

- v1/students/uuid/student-650127474515 -> 200
- v1/students/uuid/student-650127474515/outings -> 500

---

에러코드
> {
    "code": -1000,
    "message": "AttributeError(\"'NoneType' object has no attribute 'Grade'\")",
    "status": 500
}

**Comment by mallycrip** [comment]
어제 새벽에 고친거 푸시 할게염
