### ISSUE TITLE
CreateOuting 새 외출증 생성 시 redis 부분에서 오류 뜸. DB엔 저장은 된 듯 (다시하면 409)

### ISSUE THREAD

**Issue by parkjinhong03** [DMS-SMS/v1-service-outing#76]
<img width="1574" alt="스크린샷 2020-12-06 오후 4 35 10" src="https://user-images.githubusercontent.com/48676834/101274496-d5426680-37e1-11eb-9bbf-f15194a7a56f.png">
다음은 CreateOuting jaeger중 Redis (save) 부분 캡쳐본, 실행 환경은 본인 컴퓨터 로컬 서버

**Comment by mallycrip** [comment]
Consul에 값 저장시 Redis는 DB 부분을 0~16  사이의 정수 값으로 해야함. 
이로 인해 버그남
