### ISSUE TITLE
GetStudentOutings MySQL Connection 오류 (MySQL server has gone away)

### ISSUE THREAD

**Issue by parkjinhong03** [DMS-SMS/v1-service-outing#91]
처음엔 "MySQL server has gone away" 오류 뜨다가
> http://54.180.165.105:16686/trace/749ef7e657ed0183

그 이후론 "Can't reconnect until invalid transaction is rolled back" 오류 뜸
>http://54.180.165.105:16686/trace/10f1aad9cadcff95

**Comment by mallycrip** [comment]
sqlalchemy expire_on_commit=false 로 Issue 해결
