### ISSUE TITLE
GetStudentOutings 외부 서비스 연결 오류 (InactiveRpcError of RPC that terminated with)

### ISSUE THREAD

**Issue by parkjinhong03** [DMS-SMS/v1-service-outing#92]
이 오류같은 경우, 중간에 Auth Service를 재시작(IP 변경됨)하면 뜨는 듯 합니다. 혹시 **Consul에서 서비스 조회하는 로직**을 알 수 있을까요?
> http://54.180.165.105:16686/trace/1f48207bc659e711

<br>

_참고로, Schedule이나 Announcement에서는 이러한 상황에서도 오류 없이 잘 동작함_

**Comment by mallycrip** [comment]
외부 서비스 변경시 조회하는 로직을 구현하지 않았습니다. 구현 하는 부분은 어렵지 않으니 금방 고칠게요.
